try
zYoma/gophermart pull request #1
Opened 2024-02-09 13:20 UTC by zYoma

2024-02-13 15:00 UTC, bambruysk requested changes
Нужно доработать. Особенно в части архитектуры

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/create_order_test.go
> +		})
так совсем неудобно - да и mock.Anything -  не очено хорощо тестит

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/create_order_test.go
> +
лучше создавать мок на каждый тесткейс тут, в тесткейсе модно прописать ожидаемую ошибку от него, параметры. к тому же тесты так не будут влиять дрпуг на друга через общий объект

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/register.go
> +		validateErr := err.(validator.ValidationErrors)
приведение без проверки на успех опасно паникой

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/loyalty_task.go
> +func (h *HandlerService) UpdateOrdersStatus(wg *sync.WaitGroup) {
у нас тут прям божественный клас получился, и входящие запрсы обрабатывает и систему лояльности сам ходит

Эта джоба явно неотвествееность этого пакета и этих хендлеров
Лучше вынести ее с слой бизнес-логики

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/loyalty_task.go
> +
лучшще их ловтить где-то в одном месте иначе покрыть тестами сложно

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/loyalty_task.go
> +	ticker := time.NewTicker(60 * time.Second)
это лучше вынести в конфиг

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/loyalty_task.go
> +			registeredOrders := h.getOrders()
если здесь придет сгнал на отмену, то getOrders продолжит обрабатываться - лучше бы прбросить туда контекст который отменяется по сигналу завергения

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/loyalty_task.go
> +	}
лучше вернуть ошибку, а в цикле ее залогировать

2024-02-13 15:00 UTC, bambruysk commented on internal/handlers/loyalty_task.go
> +		logger.Log.Error("не удалось обновить заказ", zap.Error(err))
здесь return потерялся

2024-02-13 15:00 UTC, bambruysk commented on internal/storage/postgres/postgres.go
> +var ErrWithdrawalsNotFound = errors.New("withdrawals not found")
лучше объединить в группу var ( )

2024-02-13 15:00 UTC, bambruysk commented on internal/storage/migrations/20240209140150_change_types.sql
> +ALTER COLUMN sum TYPE FLOAT USING sum::INTEGER;
Использовать  float  для денег это прям антипаттерн) могу быть ошибки округления, которые накапливаются

2024-02-13 15:00 UTC, bambruysk commented on internal/storage/postgres/postgres.go
> +	defer s.mutex.Unlock()
а зачем?

2024-02-13 15:00 UTC, bambruysk commented on internal/integrations/loyalty/loyalty.go
> +	}
Нужно обрабатывать все статусы заказов там есть 429 - значит нужно ретраится через то время которое он указывает

И для 204 если не найден то нужно проставить статус

2024-02-13 19:53 UTC, zYoma commented on internal/handlers/create_order_test.go
> +		})
Оставил mock.Anything только для контекста, остальным аргументам передаю конкретные значения из тест кейсов

2024-02-13 19:53 UTC, zYoma commented on internal/handlers/create_order_test.go
> +
Спасибо за подсказку, я тоже не мог понять почему так сложно) Перенес, передаю значения из тест кейсов

2024-02-13 19:53 UTC, zYoma commented on internal/handlers/register.go
> +		validateErr := err.(validator.ValidationErrors)
Добавил тут проверку

2024-02-13 19:54 UTC, zYoma commented on internal/handlers/loyalty_task.go
> +func (h *HandlerService) UpdateOrdersStatus(wg *sync.WaitGroup) {
Вынес в отдельный пакет, если ожидалось что-то другое, напиши чуть подробнее

2024-02-13 19:55 UTC, zYoma commented on internal/handlers/loyalty_task.go
> +
Заменил это на signal.NotifyContext для прерывания контекста

2024-02-13 19:55 UTC, zYoma commented on internal/handlers/loyalty_task.go
> +	ticker := time.NewTicker(60 * time.Second)
вынес в конфиг

2024-02-13 19:56 UTC, zYoma commented on internal/handlers/loyalty_task.go
> +			registeredOrders := h.getOrders()
Добавил контекст signal.NotifyContext, передаю его во все вызываемые функции

2024-02-13 19:57 UTC, zYoma commented on internal/handlers/loyalty_task.go
> +	}
Залогировал тут ошибку, особо не вижу смыла возвращать наверх ошибку так как это таска фоновая

2024-02-13 19:57 UTC, zYoma commented on internal/handlers/loyalty_task.go
> +		logger.Log.Error("не удалось обновить заказ", zap.Error(err))
добавил

2024-02-13 19:57 UTC, zYoma commented on internal/storage/postgres/postgres.go
> +var ErrWithdrawalsNotFound = errors.New("withdrawals not found")
понял, сделал

2024-02-13 19:58 UTC, zYoma commented on internal/storage/migrations/20240209140150_change_types.sql
> +ALTER COLUMN sum TYPE FLOAT USING sum::INTEGER;
перевел на тип NUMERIC

2024-02-13 19:58 UTC, zYoma commented on internal/storage/postgres/postgres.go
> +	defer s.mutex.Unlock()
согласен, изоляция в бд есть

2024-02-13 19:59 UTC, zYoma commented on internal/integrations/loyalty/loyalty.go
> +	}
Добвил ретраи при статусе 429.
таже добавил обновление статуса при 204

2024-02-15 08:37 UTC, bambruysk requested changes
Добавил пару замечаний. Хотелось бы чтобы хендлеры отвечаали только за работу с HTTP

в остальном очень круто

2024-02-15 08:37 UTC, bambruysk commented on internal/app/tasks/loyalty_task.go
> +func UpdateOrdersStatus(cfg *config.Config, wg *sync.WaitGroup, provider storage.Provider, orderChan chan string) {
если бы это сделать методами структуры, то WaitGroup могла бы быть в ней

2024-02-15 08:37 UTC, bambruysk commented on internal/app/tasks/loyalty_task.go
> +	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
этот контекст со стопом лучше бы пробросить сюда из мейна

2024-02-15 08:37 UTC, bambruysk commented on internal/app/tasks/loyalty_task.go
> +		return []string{}
лучше nil тут вернуть

2024-02-15 08:37 UTC, bambruysk commented on internal/config/config.go
> +		} else {
else лишняя

2024-02-15 08:37 UTC, bambruysk commented on internal/integrations/loyalty/loyalty.go
> +				broadcastResume(pauseChan) // Отправляем сигнал о возобновлении работы всем горутинам
Не всем, а какой-то одной. Так как если несколько горутин блокируются на чтение этого канала то прочитает - толькj одна. Для броадкаста лучше использовать sync.Cond

2024-02-15 08:37 UTC, bambruysk commented on internal/app/tasks/loyalty_task.go
> +func UpdateOrdersStatus(cfg *config.Config, wg *sync.WaitGroup, provider storage.Provider, orderChan chan string) {
И еще - лучше сделать добавление заказа через обычный неблокирующий вызов, то есть сделать метод который будет вызываться в хендлерах на добавление. Так как канал достаточно несвязанная штука с хендлерами. 
В целом же, лучше в решении этой задачи сделать более просто. Мы создали же в базе order  со статусом NEW -  вот и находим здесь order c этим статусом и обрабатываем. Так же проще будет.

2024-02-15 12:02 UTC, zYoma commented on internal/app/tasks/loyalty_task.go
> +func UpdateOrdersStatus(cfg *config.Config, wg *sync.WaitGroup, provider storage.Provider, orderChan chan string) {
1) Добавил отдельную структуру TaskService в которой инкапсулировал провайдер, настройки и WaitGroup. Сделал отдельные функции методами.Теперь передавать между функиями нужно меньше аргументов.

2) избавился от канала для созданных заказов. Делаю неблокирующий вызов при создании заказа, чтобы сразу попробовать получить по нему инфо.

2024-02-15 12:03 UTC, zYoma commented on internal/app/tasks/loyalty_task.go
> +	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
Вынес в main, оттуда прокидываю

2024-02-15 12:03 UTC, zYoma commented on internal/app/tasks/loyalty_task.go
> +		return []string{}
поменял на nil

2024-02-15 12:03 UTC, zYoma commented on internal/config/config.go
> +		} else {
убрал

2024-02-15 12:05 UTC, zYoma commented on internal/integrations/loyalty/loyalty.go
> +				broadcastResume(pauseChan) // Отправляем сигнал о возобновлении работы всем горутинам
Изменил реализацию, использовал sync.NewCond
Вообще, нужно распределенное хранилище, если у нас несколько подов, вероятно, можно использовать редис. Не будем переусложнять.

2024-02-18 13:22 UTC, bambruysk approved these changes
Принято

2024-02-18 14:11 UTC, merged